# generated by datamodel-codegen:
#   filename:  report.yaml
#   timestamp: 2026-09-21T10:33:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class FailOn(Enum):
    ERROR = "error"
    WARNING = "warning"


class Status(Enum):
    PASSED = "passed"
    FAILED = "failed"
    NEEDS_REVIEW = "needs-review"
    NOT_APPLICABLE = "not-applicable"
    BLOCKED = "blocked"


class Severity(Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class Location(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    uri: Annotated[str, Field(title="Uri")]
    path: Annotated[str, Field(title="Path")] = ""
    line: Annotated[int | None, Field(ge=1)] = None
    """
    One-based original-source position, or null when unavailable.
    """
    column: Annotated[int | None, Field(ge=1)] = None
    """
    One-based original-source position, or null when unavailable.
    """


class Counts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    passed: Annotated[int, Field(ge=0)] = 0
    failed: Annotated[int, Field(ge=0)] = 0
    needs_review: Annotated[int, Field(alias="needs-review", ge=0)] = 0
    not_applicable: Annotated[int, Field(alias="not-applicable", ge=0)] = 0
    blocked: Annotated[int, Field(ge=0)] = 0


class Finding(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rule_id: Annotated[str, Field(title="Rule Id")]
    profile: Annotated[str, Field(title="Profile")]
    status: Annotated[Status, Field(title="Status")]
    severity: Annotated[Severity, Field(title="Severity")]
    message: Annotated[str, Field(title="Message")]
    location: Location
    suggestion: Annotated[str | None, Field(title="Suggestion")] = None
    reference: Annotated[str | None, Field(title="Reference")] = None
    instance_path: Annotated[list[str], Field(title="Instance Path")] = []


class ReportData(BaseModel):
    """
    Validation assessment fields populated by the validator before summary calculation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    schema_version: Annotated[str, Field(title="Schema Version")] = "1.0"
    validator_version: Annotated[str, Field(title="Validator Version")] = "0.1.0"
    source: Annotated[str, Field(title="Source")]
    entrypoint: Annotated[str | None, Field(title="Entrypoint")] = None
    profiles: Annotated[dict[str, str], Field(title="Profiles")] = {}
    tool_versions: Annotated[dict[str, str], Field(title="Tool Versions")] = {}
    dependencies: Annotated[list[str], Field(title="Dependencies")] = []
    dependency_coverage: Annotated[str, Field(title="Dependency Coverage")] = (
        "Root and resolved process sources; not a complete import/include manifest."
    )
    findings: Annotated[
        list[Finding], Field(title="Findings", validate_default=True)
    ] = []
    operational_failure: Annotated[bool, Field(title="Operational Failure")] = False


class Report(ReportData):
    """
    EOAP Validator JSON output report, schema version 1.0. Counts and exit_code describe the selected failure threshold.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    counts: Counts
    exit_code: Annotated[int, Field(ge=0, le=2)] = 0
    fail_on: FailOn = FailOn.ERROR
    schema_version: Annotated[str, Field(title="Schema Version")] = "1.0"
    validator_version: Annotated[str, Field(title="Validator Version")] = "0.1.0"
    source: Annotated[str, Field(title="Source")]
    entrypoint: Annotated[str | None, Field(title="Entrypoint")] = None
    profiles: Annotated[dict[str, str], Field(title="Profiles")] = {}
    tool_versions: Annotated[dict[str, str], Field(title="Tool Versions")] = {}
    dependencies: Annotated[list[str], Field(title="Dependencies")] = []
    dependency_coverage: Annotated[str, Field(title="Dependency Coverage")] = (
        "Root and resolved process sources; not a complete import/include manifest."
    )
    findings: Annotated[
        list[Finding], Field(title="Findings", validate_default=True)
    ] = []
    operational_failure: Annotated[bool, Field(title="Operational Failure")] = False
